### ISSUE TITLE
Inherit from bootstrap theme KO

### ISSUE THREAD

**Issue by gcegithub** [getgrav/grav-theme-bootstrap#5]
> > > according to : [Grav theme inheritance](http://getgrav.org/blog/theme-development-with-inheritance) 
# INFO:

=>pluging  Bootstrapper eneble version: 1.1.0
=>template bootstrap version: 1.4.0
=>new theme : mytheme with mytheme.yaml

``` yaml
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/mytheme
         - user/themes/bootstrap
```

=>system.yaml : pages: theme: mytheme
# ISSUE:

bootstrap framework is not loaded but the content is loaded.
![isseubootstrap](https://cloud.githubusercontent.com/assets/8493373/10263911/52586956-69fe-11e5-9c26-2e458a99991b.jpg)

Alternative: If you load the antimatter theme from the mytheme, it works 

``` yaml
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
         - user/themes/mytheme
         - user/themes/antimatter
```
# SOLUTION

Not identified yet
