### ISSUE TITLE
placeholder not showing on textareas 

### ISSUE THREAD

**Issue by z3cka** [getgrav/grav-theme-bootstrap#6]
It seems that 

``` yaml
- name: detailed-description
      label: Detailed description
      placeholder: 'including learning outcomes, for proposal review (up to 250 words)'
      type: textarea
```

outputs:

``` html
<textarea rows="10" class="form-control" name="detailed-description"></textarea>
```

missing the placeholder attribute

I think the solution is to modify or remove the `textarea/textarea.html.twig` directory and/or file. @rhukster  ?

issue moved from https://github.com/getgrav/grav-plugin-form/issues/10
